In [1]:
import numpy as np

# 宣告陣列

In [2]:
X = np.array([1,2,3,4])
X

array([1, 2, 3, 4])

In [3]:
X = np.array([[1,2,3,4], [5,6,7,8]])
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
X = np.zeros((2,3))
X

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
X = np.ones((2,3))
X

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
X = np.random.randint(-10,10,size = (3,4))
X

array([[  3,   1,  -4,   4],
       [ -2,   8, -10,  -6],
       [  7,  -9,  -8,   1]])

In [7]:
Y = np.random.randn(1,3)
Y

array([[ 1.28526866, -0.50402433, -0.19762878]])

# 矩陣相乘

In [8]:
X = np.random.randint(-10,10,size = (3,4))
Y = np.random.randn(1,3)
Z = np.dot(Y, X)
Z

array([[ 5.03984808,  1.39045786, 11.984017  , 15.2976782 ]])

# 轉置

In [9]:
X.T

array([[-10,  -4,   4],
       [-10,   2,  -3],
       [ -1, -10,   4],
       [ -6,  -7,  -5]])

# Broadcasting example

# row/col sum 記得加上 keepdims = True 才不會降維

In [10]:
import numpy as np
X = np.random.randint(-10,10,size = (3,4))
XSum = X.sum(axis = 0) #上至下加總行，但變成了一階陣列
XSum

array([-2,  4,  7, -4])

In [11]:
XSum = X.sum(axis = 1) #左至右加總列，但變成了一階陣列
XSum

array([ 1, 12, -8])

In [12]:
XSum = X.sum(axis = 1, keepdims = True) #左至右加總列，維持原本的二階陣列
XSum

array([[ 1],
       [12],
       [-8]])

In [13]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    x = x / x_norm
    return x

In [14]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (n, m).

    Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    x_exp = np.exp(x)
    x_sum = x_exp.sum(axis = 1, keepdims = True)
    s = x_exp / x_sum   
    return s

# condition

In [15]:
(X > 0)

array([[False,  True, False,  True],
       [ True,  True,  True,  True],
       [False, False,  True, False]])

In [16]:
(X > 0).all() #全部都要滿足

False

In [17]:
(X > 0).any() #任一個滿足

True

In [18]:
mask = (X < 0) #先取得True/False陣列遮罩
X[mask] = 99   #只針對mask運算
X

array([[99,  5, 99,  2],
       [ 5,  1,  3,  3],
       [99, 99,  8, 99]])

# calculate

In [19]:
X = np.random.randint(0,2, size = (3,4))
X

array([[0, 0, 1, 1],
       [1, 1, 0, 1],
       [0, 1, 1, 0]])

In [20]:
Y = 100.0
Y

100.0

In [21]:
Z = X + Y
Z

array([[100., 100., 101., 101.],
       [101., 101., 100., 101.],
       [100., 101., 101., 100.]])

In [22]:
Z = X - Y
Z

array([[-100., -100.,  -99.,  -99.],
       [ -99.,  -99., -100.,  -99.],
       [-100.,  -99.,  -99., -100.]])

In [23]:
Z = X * Y
Z

array([[  0.,   0., 100., 100.],
       [100., 100.,   0., 100.],
       [  0., 100., 100.,   0.]])

In [24]:
Z = X / Y
Z

array([[0.  , 0.  , 0.01, 0.01],
       [0.01, 0.01, 0.  , 0.01],
       [0.  , 0.01, 0.01, 0.  ]])

# calculate2

In [25]:
Y = np.array([100.0,200.0,300.0,400.0])
Y

array([100., 200., 300., 400.])

In [26]:
X + Y

array([[100., 200., 301., 401.],
       [101., 201., 300., 401.],
       [100., 201., 301., 400.]])

In [27]:
X - Y

array([[-100., -200., -299., -399.],
       [ -99., -199., -300., -399.],
       [-100., -199., -299., -400.]])

In [28]:
X * Y

array([[  0.,   0., 300., 400.],
       [100., 200.,   0., 400.],
       [  0., 200., 300.,   0.]])

In [29]:
X / Y

array([[0.        , 0.        , 0.00333333, 0.0025    ],
       [0.01      , 0.005     , 0.        , 0.0025    ],
       [0.        , 0.005     , 0.00333333, 0.        ]])

# calculate3

In [30]:
Y = np.array([[20,30,40,50],[200,300,400,500],[2000,3000,4000,5000]])

In [31]:
X + Y

array([[  20,   30,   41,   51],
       [ 201,  301,  400,  501],
       [2000, 3001, 4001, 5000]])

In [32]:
X - Y

array([[  -20,   -30,   -39,   -49],
       [ -199,  -299,  -400,  -499],
       [-2000, -2999, -3999, -5000]])

In [33]:
#...

# 注意!! boradcast 並不是傳統矩陣運算，傳統矩陣運算請呼叫dot

In [34]:
import numpy as np
a = np.random.randint(5,size = (3,3))
b = np.random.randint(5,size = (3,1))
a

array([[2, 0, 4],
       [0, 0, 4],
       [1, 2, 0]])

In [35]:
b

array([[4],
       [1],
       [2]])

In [36]:
a * b

array([[ 8,  0, 16],
       [ 0,  0,  4],
       [ 2,  4,  0]])

In [37]:
np.dot(a,b)

array([[16],
       [ 8],
       [ 6]])

# What you need to remember:

### np.exp(x) works for any np.array x and applies the exponential function to every coordinate

### the sigmoid function and its gradient

### image2vector is commonly used in deep learning

### np.reshape is widely used. In the future, you'll see that keeping your matrix/vector dimensions straight will go toward eliminating a lot of bugs.

### numpy has efficient built-in functions

### broadcasting is extremely useful

# Reshape (引數-1代表不知size多少，自動用其他維度的size回推)

In [38]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [41]:
np.reshape(a, (1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [42]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    #v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    v = image.reshape(-1, 1)
    return v

# Loss Function

In [43]:
def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    #loss = sum(np.square(y - yhat))   
    dy = y - yhat
    loss = np.dot(dy,dy)
    return loss

In [44]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    loss = sum(np.abs(yhat - y))    
    return loss