In [161]:
import numpy as np

# 宣告陣列

In [162]:
X = np.array([1,2,3,4])
X

array([1, 2, 3, 4])

In [163]:
X = np.array([[1,2,3,4], [5,6,7,8]])
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
X = np.zeros((2,3))
X

array([[0., 0., 0.],
       [0., 0., 0.]])

In [165]:
X = np.ones((2,3))
X

array([[1., 1., 1.],
       [1., 1., 1.]])

In [166]:
X = np.random.randint(-10,10,size = (3,4))
X

array([[-10,   6,   9,  -8],
       [  6,   5,   9,   2],
       [  4,  -5, -10,  -7]])

In [167]:
Y = np.random.randn(1,3)
Y

array([[-0.19335092, -0.49182919, -0.75213302]])

# 矩陣相乘

In [7]:
X = np.random.randint(-10,10,size = (3,4))
Y = np.random.randn(1,3)
Z = np.dot(Y, X)
Z

array([[-18.48478967,  17.97642921,   0.06571263,  -1.0184872 ]])

# 轉置

In [169]:
X.T

array([[-10,   6,   4],
       [  6,   5,  -5],
       [  9,   9, -10],
       [ -8,   2,  -7]])

# Broadcasting example

# row/col sum 記得加上 keepdims = True 才不會降維

In [16]:
import numpy as np
X = np.random.randint(-10,10,size = (3,4))
XSum = X.sum(axis = 0) #上至下加總行，但變成了一階陣列
XSum

array([-7, -4,  2,  3])

In [17]:
XSum = X.sum(axis = 1) #左至右加總列，但變成了一階陣列
XSum

array([ 1, -1, -6])

In [18]:
XSum = X.sum(axis = 1, keepdims = True) #左至右加總列，維持原本的二階陣列
XSum

array([[ 1],
       [-1],
       [-6]])

In [36]:
def normalizeRows(x):
    """
    Implement a function that normalizes each row of the matrix x (to have unit length).
    
    Argument:
    x -- A numpy matrix of shape (n, m)
    
    Returns:
    x -- The normalized (by row) numpy matrix. You are allowed to modify x.
    """
    x_norm = np.linalg.norm(x, axis = 1, keepdims = True)
    x = x / x_norm
    return x

In [37]:
def softmax(x):
    """Calculates the softmax for each row of the input x.

    Your code should work for a row vector and also for matrices of shape (n, m).

    Argument:
    x -- A numpy matrix of shape (n,m)

    Returns:
    s -- A numpy matrix equal to the softmax of x, of shape (n,m)
    """
    x_exp = np.exp(x)
    x_sum = x_exp.sum(axis = 1, keepdims = True)
    s = x_exp / x_sum   
    return s

# condition

In [172]:
(X > 0)

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [173]:
(X > 0).all() #全部都要滿足

False

In [174]:
(X > 0).any() #任一個滿足

True

In [175]:
mask = (X < 0) #先取得True/False陣列遮罩
X[mask] = 99   #只針對mask運算
X

array([[99,  6,  9, 99],
       [ 6,  5,  9,  2],
       [ 4, 99, 99, 99]])

# calculate

In [204]:
X = np.random.randint(0,2, size = (3,4))
X

array([[1, 1, 1, 1],
       [0, 1, 1, 0],
       [0, 0, 1, 1]])

In [205]:
Y = 100.0
Y

100.0

In [206]:
Z = X + Y
Z

array([[101., 101., 101., 101.],
       [100., 101., 101., 100.],
       [100., 100., 101., 101.]])

In [207]:
Z = X - Y
Z

array([[ -99.,  -99.,  -99.,  -99.],
       [-100.,  -99.,  -99., -100.],
       [-100., -100.,  -99.,  -99.]])

In [208]:
Z = X * Y
Z

array([[100., 100., 100., 100.],
       [  0., 100., 100.,   0.],
       [  0.,   0., 100., 100.]])

In [209]:
Z = X / Y
Z

array([[0.01, 0.01, 0.01, 0.01],
       [0.  , 0.01, 0.01, 0.  ],
       [0.  , 0.  , 0.01, 0.01]])

# calculate2

In [217]:
Y = np.array([100.0,200.0,300.0,400.0])
Y

array([100., 200., 300., 400.])

In [218]:
X + Y

array([[101., 201., 301., 401.],
       [100., 201., 301., 400.],
       [100., 200., 301., 401.]])

In [219]:
X - Y

array([[ -99., -199., -299., -399.],
       [-100., -199., -299., -400.],
       [-100., -200., -299., -399.]])

In [220]:
X * Y

array([[100., 200., 300., 400.],
       [  0., 200., 300.,   0.],
       [  0.,   0., 300., 400.]])

In [221]:
X / Y

array([[0.01      , 0.005     , 0.00333333, 0.0025    ],
       [0.        , 0.005     , 0.00333333, 0.        ],
       [0.        , 0.        , 0.00333333, 0.0025    ]])

# calculate3

In [223]:
Y = np.array([[20,30,40,50],[200,300,400,500],[2000,3000,4000,5000]])

In [224]:
X + Y

array([[  21,   31,   41,   51],
       [ 200,  301,  401,  500],
       [2000, 3000, 4001, 5001]])

In [225]:
X - Y

array([[  -19,   -29,   -39,   -49],
       [ -200,  -299,  -399,  -500],
       [-2000, -3000, -3999, -4999]])

In [1]:
#...

# 注意!! boradcast 並不是傳統矩陣運算，傳統矩陣運算請呼叫dot

In [3]:
import numpy as np
a = np.random.randint(5,size = (3,3))
b = np.random.randint(5,size = (3,1))
a

array([[2, 3, 0],
       [2, 4, 4],
       [2, 0, 1]])

In [4]:
b

array([[4],
       [4],
       [3]])

In [5]:
a * b

array([[ 8, 12,  0],
       [ 8, 16, 16],
       [ 6,  0,  3]])

In [6]:
np.dot(a,b)

array([[20],
       [36],
       [11]])

# What you need to remember:

### np.exp(x) works for any np.array x and applies the exponential function to every coordinate

### the sigmoid function and its gradient

### image2vector is commonly used in deep learning

### np.reshape is widely used. In the future, you'll see that keeping your matrix/vector dimensions straight will go toward eliminating a lot of bugs.

### numpy has efficient built-in functions

### broadcasting is extremely useful

# Reshape (引數-1代表不知size多少，自動用其他維度的size回推)

In [20]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
a.reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [24]:
a.reshape(-1,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [28]:
np.reshape(a, (1,-1))

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [38]:
def image2vector(image):
    """
    Argument:
    image -- a numpy array of shape (length, height, depth)
    
    Returns:
    v -- a vector of shape (length*height*depth, 1)
    """
    #v = image.reshape(image.shape[0] * image.shape[1] * image.shape[2], 1)
    v = image.reshape(-1, 1)
    return v

# Loss Function

In [34]:
def L2(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L2 loss function defined above
    """
    #loss = sum(np.square(y - yhat))   
    dy = y - yhat
    loss = np.dot(dy,dy)
    return loss

In [35]:
def L1(yhat, y):
    """
    Arguments:
    yhat -- vector of size m (predicted labels)
    y -- vector of size m (true labels)
    
    Returns:
    loss -- the value of the L1 loss function defined above
    """
    loss = sum(np.abs(yhat - y))    
    return loss