In [161]:
import numpy as np

# 宣告陣列

In [162]:
X = np.array([1,2,3,4])
X

array([1, 2, 3, 4])

In [163]:
X = np.array([[1,2,3,4], [5,6,7,8]])
X

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [164]:
X = np.zeros((2,3))
X

array([[0., 0., 0.],
       [0., 0., 0.]])

In [165]:
X = np.ones((2,3))
X

array([[1., 1., 1.],
       [1., 1., 1.]])

In [166]:
X = np.random.randint(-10,10,size = (3,4))
X

array([[-10,   6,   9,  -8],
       [  6,   5,   9,   2],
       [  4,  -5, -10,  -7]])

In [167]:
Y = np.random.randn(1,3)
Y

array([[-0.19335092, -0.49182919, -0.75213302]])

# 內積

In [168]:
Z = np.dot(Y, X)
Z

array([[-4.02599805,  0.14141366,  1.35470926,  5.82808014]])

# 轉置

In [169]:
X.T

array([[-10,   6,   4],
       [  6,   5,  -5],
       [  9,   9, -10],
       [ -8,   2,  -7]])

# Broadcasting example

# row/col sum

In [170]:
XSum = X.sum(axis = 0) #上至下加總行
XSum

array([  0,   6,   8, -13])

In [171]:
XSum = X.sum(axis = 1) #左至右加總列，但也是用一列表達結果
XSum

array([ -3,  22, -18])

# condition

In [172]:
(X > 0)

array([[False,  True,  True, False],
       [ True,  True,  True,  True],
       [ True, False, False, False]])

In [173]:
(X > 0).all() #全部都要滿足

False

In [174]:
(X > 0).any() #任一個滿足

True

In [175]:
mask = (X < 0) #先取得True/False陣列遮罩
X[mask] = 99   #只針對mask運算
X

array([[99,  6,  9, 99],
       [ 6,  5,  9,  2],
       [ 4, 99, 99, 99]])

# calculate

In [204]:
X = np.random.randint(0,2, size = (3,4))
X

array([[1, 1, 1, 1],
       [0, 1, 1, 0],
       [0, 0, 1, 1]])

In [205]:
Y = 100.0
Y

100.0

In [206]:
Z = X + Y
Z

array([[101., 101., 101., 101.],
       [100., 101., 101., 100.],
       [100., 100., 101., 101.]])

In [207]:
Z = X - Y
Z

array([[ -99.,  -99.,  -99.,  -99.],
       [-100.,  -99.,  -99., -100.],
       [-100., -100.,  -99.,  -99.]])

In [208]:
Z = X * Y
Z

array([[100., 100., 100., 100.],
       [  0., 100., 100.,   0.],
       [  0.,   0., 100., 100.]])

In [209]:
Z = X / Y
Z

array([[0.01, 0.01, 0.01, 0.01],
       [0.  , 0.01, 0.01, 0.  ],
       [0.  , 0.  , 0.01, 0.01]])

# calculate2

In [217]:
Y = np.array([100.0,200.0,300.0,400.0])
Y

array([100., 200., 300., 400.])

In [218]:
X + Y

array([[101., 201., 301., 401.],
       [100., 201., 301., 400.],
       [100., 200., 301., 401.]])

In [219]:
X - Y

array([[ -99., -199., -299., -399.],
       [-100., -199., -299., -400.],
       [-100., -200., -299., -399.]])

In [220]:
X * Y

array([[100., 200., 300., 400.],
       [  0., 200., 300.,   0.],
       [  0.,   0., 300., 400.]])

In [221]:
X / Y

array([[0.01      , 0.005     , 0.00333333, 0.0025    ],
       [0.        , 0.005     , 0.00333333, 0.        ],
       [0.        , 0.        , 0.00333333, 0.0025    ]])

# calculate3

In [223]:
Y = np.array([[20,30,40,50],[200,300,400,500],[2000,3000,4000,5000]])

In [224]:
X + Y

array([[  21,   31,   41,   51],
       [ 200,  301,  401,  500],
       [2000, 3000, 4001, 5001]])

In [225]:
X - Y

array([[  -19,   -29,   -39,   -49],
       [ -200,  -299,  -399,  -500],
       [-2000, -3000, -3999, -4999]])

In [ ]:
#...